# NumPy Tutorial
YouTube : https://www.youtube.com/watch?v=Rbh1rieb3zc&t=1368s

GeeksforGeeks : https://www.geeksforgeeks.org/python-numpy/

In [1]:
import numpy as np

# np.int64 is 64 Bits

In [2]:
MyArr = np.array([[234,4,6342,234,234,234,]], np.int64)

In [3]:
MyArr

array([[ 234,    4, 6342,  234,  234,  234]], dtype=int64)

In [4]:
MyArr[0]

array([ 234,    4, 6342,  234,  234,  234], dtype=int64)

In [5]:
MyArr[0, 4]

234

# shape

In [6]:
MyArr.shape

(1, 6)

# dtype

In [7]:
MyArr.dtype

dtype('int64')

In [8]:
MyArr[0, 4] = 782

In [9]:
MyArr

array([[ 234,    4, 6342,  234,  782,  234]], dtype=int64)

# Multiple dimantion array

In [10]:
listArry = np.array([[1,2,3], [5,3,5], [0,3,1]])

In [11]:
listArry

array([[1, 2, 3],
       [5, 3, 5],
       [0, 3, 1]])

# size
In Python, numpy.size() function count the number of elements along a given axis.

    Synatx: numpy.size(arr, axis=None)

    Parameters:
    arr: [array_like] Input data.
    axis: [int, optional] Axis along which the elements are counted. By default, give the total number of elements.

    Returns: [int] Return the number of elements along a given axis.

In [12]:
listArry.size

9

In [13]:
listArry.shape

(3, 3)

In [14]:
listArry.dtype

dtype('int32')

# Add a Dictonary

In [15]:
np.array({34, 23})

array({34, 23}, dtype=object)

In [16]:
zerros = np.zeros((2,5))

In [17]:
zerros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
zerros.size

10

In [19]:
zerros.shape

(2, 5)

# arange 
arange([start,] stop[, step,][, dtype]) : Returns an array with evenly spaced elements as per the interval. The interval mentioned is half opened i.e. [Start, Stop)
Parameters :

start : [optional] start of interval range. By default start = 0
stop  : end of interval range
step  : [optional] step size of interval. By default step size = 1,  
For any output out, this is the distance between two adjacent values, out[i+1] - out[i]. 
dtype : type of output array

Return:

Array of evenly spaced values.
Length of array being generated  = Ceil((Stop - Start) / Step)

In [20]:
range = np.arange(10)

In [21]:
range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# linspace

numpy.linspace(start, stop, num = 50, endpoint = True, retstep = False, dtype = None) : Returns number spaces evenly w.r.t interval. Similar to arange but instead of step it uses sample number.
Parameters :

-> start  : [optional] start of interval range. By default start = 0
-> stop   : end of interval range
-> restep : If True, return (samples, step). By deflut restep = False
-> num    : [int, optional] No. of samples to generate
-> dtype  : type of output array

Return :

-> ndarray
-> step : [float, optional], if restep = True

In [22]:
lspace = np.linspace(1,50,10)

In [23]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [24]:
lspace = np.linspace(100,1000,2)

In [25]:
lspace

array([ 100., 1000.])

# empty
numpy.empty(shape, dtype = float, order = ‘C’) : Return a new array of given shape and type, with random values.
Parameters :

-> shape : Number of rows
-> order : C_contiguous or F_contiguous
-> dtype : [optional, float(by Default)] Data type of returned array.  

In [26]:
empty = np.empty((4,6))

In [27]:
empty

array([[3.52554352e-289, 4.26745368e-316, 1.64425047e-319,
        4.26744004e-316, 1.84489092e-316, 0.00000000e+000],
       [3.60920466e-313, 1.32334647e+255, 3.60739305e-313,
        1.32442401e+255, 1.30687910e+255, 1.30376390e-309],
       [            nan, 1.44635488e-307, 3.33773471e-307,
        4.22793572e-307, 4.22794251e-307, 1.05697544e-307],
       [9.34603679e-307, 1.24610994e-306, 1.42419938e-306,
        9.34608432e-307, 1.24611470e-306, 0.00000000e+000]])

# empty_like
numpy.empty_like(a, dtype = None, order = ‘K’, subok = True) : Return a new array with the same shape and type as a given array.
Parameters :

shape : Number of rows
order : C_contiguous or F_contiguous
dtype : [optional, float(by Default)] Data type of returned array.  
subok : [bool, optional] to make subclass of a or not

Return :

array with the same shape and type as a given array.

In [28]:
emp_like = np.empty_like(lspace)

In [29]:
emp_like

array([ 100., 1000.])

# identity
numpy.identity(n, dtype = None) : Return a identity matrix i.e. a square matrix with ones on the main daignol.
Parameters :

n     : [int] Dimension n x n of output array  
dtype : [optional, float(by Default)] Data type of returned array.  

Returns :

identity array of dimension n x n,  with its main diagonal set to one, and all other elements 0.

In [30]:
ide = np.identity(45)

In [31]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [32]:
ide.shape

(45, 45)

In [33]:
ide.size

2025

# reshape
numpy.reshape(array, shape, order = ‘C’) : shapes an array without changing data of array.

Parameters :

array : [array_like]Input array
shape : [int or tuples of int] e.g. if we are aranging an array with 10 elements then shaping
        it like numpy.reshape(4, 8) is wrong; we can 
order  : [C-contiguous, F-contiguous, A-contiguous; optional]         
         C-contiguous order in memory(last index varies the fastest)
         C order means that operating row-rise on the array will be slightly quicker
         FORTRAN-contiguous order in memory (first index varies the fastest).
         F order means that column-wise operations will be faster. 
         ‘A’ means to read / write the elements in Fortran-like index order if,
         array is Fortran contiguous in memory, C-like order otherwise

Return :

Array which is reshaped without changing the data.

In [34]:
array = np.arange(99)

In [35]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
array = array.reshape(3,33)

In [37]:
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

# Traceback!!!
I have leave this error for understanding what is going on.

In [38]:
array.reshape(3,31)

ValueError: cannot reshape array of size 99 into shape (3,31)

# ravel
numpy.ravel(array, order = ‘C’) : returns contiguous flattened array(1D array with all the input-array elements and with the same type as it). A copy is made only if needed.

Parameters :

array : [array_like]Input array. 
order : [C-contiguous, F-contiguous, A-contiguous; optional]         
         C-contiguous order in memory(last index varies the fastest)
         C order means that operating row-rise on the array will be slightly quicker
         FORTRAN-contiguous order in memory (first index varies the fastest).
         F order means that column-wise operations will be faster. 
         ‘A’ means to read / write the elements in Fortran-like index order if,
         array is Fortran contiguous in memory, C-like order otherwise

Return :

Flattened array having same type as the Input array and and order as per choice. 

In [39]:
array.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# Axis 0 & 1

In [40]:
x = [[1,23,2], [123,4,56], [223,234,5]]

In [41]:
ar = np.array(x)

In [42]:
ar

array([[  1,  23,   2],
       [123,   4,  56],
       [223, 234,   5]])

In [43]:
ar.sum(axis = 0)

array([347, 261,  63])

In [44]:
ar.sum(axis = 1)

array([ 26, 183, 462])

# narray.T
With the help of Numpy ndarray.T object, we can make a Transpose of an array having dimension greater than or equal to 2.

    Syntax : ndarray.T

    Return : Transpose of an array

In [45]:
ar.T

array([[  1, 123, 223],
       [ 23,   4, 234],
       [  2,  56,   5]])

# numpy.ndarray.flat
numpy.ndarray.flat() : 1_D iterator over N-dimensional arrays.
It is not a subclass of, Python’s built-in iterator object, otherwise it a numpy.flatiter instance.

Parameters :

index : [tuple(int)] index of the values to iterate

In [51]:
flat = ar.flat

In [52]:
for i in flat:
    print(i)

1
23
2
123
4
56
223
234
5


# numpy.ndarray.ndim
numpy.ndarray.ndim() function return the number of dimensions of an array.

    Syntax : numpy.ndarray.ndim(arr)

    Parameters :
    arr : [array_like] Input array. If it is not already an ndarray, a conversion is attempted.

    Return : [int] Return the number of dimensions in arr. 

In [54]:
ar.ndim

2

In [56]:
ar.size

9

# numpy.ndarray.nbytes
Total bytes consumed by the elements of the array.

Notes

Does not include memory consumed by non-element attributes of the array object.

In [57]:
ar.nbytes

36

# np.argmax()
numpy.argmax(array, axis = None, out = None) : Returns indices of the max element of the array in a particular axis.
Parameters :

array : Input array to work on 
axis  : [int, optional]Along a specified axis like 0 or 1
out   : [array optional]Provides a feature to insert output to the out
          array and it should be of appropriate shape and dtype

Return :

Array of indices into the array with same shape as array.shape
 with the dimension along axis removed.

In [61]:
one = np.array([223,4235,532,23,235,234])

In [62]:
one.argmax()

1

# np.argmin()
numpy.argmin(array, axis = None, out = None) : Returns indices of the min element of the array in a particular axis.
Parameters :

array : Input array to work on 
axis  : [int, optional]Along a specified axis like 0 or 1
out   : [array optional]Provides a feature to insert output to the out
          array and it should be of appropriate shape and dtype

Return :

Array of indices into the array with same shape as array.shape
 with the dimension along axis removed.

In [63]:
one.argmin()

3

# np.argsort()
numpy.argsort() function is used to perform an indirect sort along the given axis using the algorithm specified by the kind keyword. It returns an array of indices of the same shape as arr that that would sort the array.

    Syntax : numpy.argsort(arr, axis=-1, kind=’quicksort’, order=None)

    Parameters :
    arr : [array_like] Input array.
    axis : [int or None] Axis along which to sort. If None, the array is flattened before sorting. The default is -1, which sorts along the last axis.
    kind : [‘quicksort’, ‘mergesort’, ‘heapsort’]Selection algorithm. Default is ‘quicksort’.
    order : [str or list of str] When arr is an array with fields defined, this argument specifies which fields to compare first, second, etc.

    Return : [index_array, ndarray] Array of indices that sort arr along the specified axis.If arr is one-dimensional then arr[index_array] returns a sorted arr.

In [64]:
one.argsort()

array([3, 0, 5, 4, 2, 1], dtype=int32)

# Test

In [68]:
ar

array([[  1,  23,   2],
       [123,   4,  56],
       [223, 234,   5]])

In [70]:
ar.argmin()

0

In [71]:
ar.argmax()

7

In [72]:
ar.argmax(axis = 0)

array([2, 2, 1], dtype=int32)

In [74]:
ar.argsort(axis = 1)

array([[0, 2, 1],
       [1, 2, 0],
       [2, 0, 1]], dtype=int32)

In [76]:
ar.ravel()

array([  1,  23,   2, 123,   4,  56, 223, 234,   5])

In [79]:
ar.reshape((9,1))

array([[  1],
       [ 23],
       [  2],
       [123],
       [  4],
       [ 56],
       [223],
       [234],
       [  5]])

# OPERATIONS

In [80]:
ar

array([[  1,  23,   2],
       [123,   4,  56],
       [223, 234,   5]])

In [81]:
ar2 = np.array([[  3241324,  23423,   3422],
       [122343,   4234,  56342],
       [222343, 23324,   5432]])

In [82]:
ar + ar2

array([[3241325,   23446,    3424],
       [ 122466,    4238,   56398],
       [ 222566,   23558,    5437]])

In [83]:
ar * ar2

array([[ 3241324,   538729,     6844],
       [15048189,    16936,  3155152],
       [49582489,  5457816,    27160]])

In [84]:
np.sqrt(ar2)

array([[1800.36774021,  153.0457448 ,   58.49786321],
       [ 349.77564238,   65.06919394,  237.3646983 ],
       [ 471.53260757,  152.7219696 ,   73.70210309]])

In [86]:
ar2.sum()

3702187

In [87]:
ar2.max()

3241324

In [88]:
ar2.min()

3422

In [97]:
ar

array([[  1,  23,   2],
       [123,   4,  56],
       [223, 234,   5]])

In [98]:
np.where(ar > 200)

(array([2, 2], dtype=int32), array([0, 1], dtype=int32))

In [94]:
type(np.where(ar > 100000))

tuple

In [93]:
np.count_nonzero(ar)

9

In [99]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int32),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int32))

# Less Size Consuming than regular Python
Prove

In [100]:
import sys

In [101]:
py_array = [0, 2, 4, 55]

In [102]:
np_array = np.array(py_array)

In [108]:
sys.getsizeof(1) * len(py_array)

56

In [110]:
np_array.itemsize * np_array.size

16